### ISSUE TITLE
`:not` chaining eventually breaks highlighting

### ISSUE THREAD

**Issue by JonathanWolfe** [azat-io/atom-language-postcss#9]
If you chain enough `:not()` selectors eventually the whole file will become improperly highlighted.

**custom-elements-are-block.css**

``` css
*:not(a):not(abbr):not(acronym):not(address):not(applet):not(area):not(article):not(aside):not(audio):not(b):not(base):not(basefont):not(bdi):not(bdo):not(bgsound):not(big):not(blink):not(blockquote):not(body):not(br):not(button):not(canvas):not(caption):not(center):not(cite):not(code):not(col):not(colgroup):not(command):not(content):not(data):not(datalist):not(dd):not(del):not(details):not(dfn):not(dialog):not(dir):not(div):not(dl):not(dt):not(element):not(em):not(embed):not(fieldset):not(figcaption):not(figure):not(font):not(footer):not(form):not(frame):not(frameset):not(h1):not(h2):not(h3):not(h4):not(h5):not(h6):not(head):not(header):not(hgroup):not(hr):not(html):not(i):not(iframe):not(image):not(img):not(input):not(ins):not(isindex):not(kbd):not(keygen):not(label):not(legend):not(li):not(link):not(listing):not(main):not(map):not(map):not(mark):not(marquee):not(menu):not(menuitem):not(meta):not(meter):not(multicol):not(nav):not(nobr):not(noembed):not(noframes):not(noscript):not(object):not(ol):not(optgroup):not(option):not(output):not(p):not(param):not(picture):not(plaintext):not(pre):not(progress):not(q):not(rb):not(rp):not(rt):not(rtc):not(ruby):not(s):not(samp):not(script):not(section):not(select):not(shadow):not(small):not(source):not(spacer):not(span):not(strike):not(strong):not(style):not(sub):not(summary):not(sup):not(table):not(tbody):not(td):not(template):not(textarea):not(tfoot):not(th):not(thead):not(time):not(title):not(tr):not(track):not(tt):not(u):not(ul):not(var):not(var):not(video):not(wbr):not(xmp) {
    position: relative;
    display: block;
}
```

**results.png**
![screen shot 2016-01-26 at 10 15 23 am](https://cloud.githubusercontent.com/assets/1449779/12584490/be8b3c36-c415-11e5-8c4d-a7ef82a05d49.png)
